apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsexamapp
  namespace: webapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopsexamapp
  template:
    metadata:
      labels:
        app: devopsexamapp
    spec:
      containers:
      - name: devopsexamapp
        image: kastrov/devopsexamapp:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: devopsexamapp-config
        - secretRef:
            name: devopsexamapp-secrets
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "sleep 30"] # Wait for MySQL to be ready
