apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsexamapp
  namespace: devopsexamapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopsexamapp
  template:
    metadata:
      labels:
        app: devopsexamapp
    spec:
      containers:
      - name: devopsexamapp
        image: kastrov/devopsexamapp:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: devopsexamapp-config
        - secretRef:
            name: devopsexamapp-secrets
      imagePullSecrets:
      - name: dockerhub-creds
