apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: devops-exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: 289095007317.dkr.ecr.ap-south-1.amazonaws.com/devopsexam:latest
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: rootpassword
        - name: DB_NAME
          value: devops_exam
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: devops-exam
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
  - port: 80
    targetPort: 5000

  
