apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: devops-exam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: 289095007317.dkr.ecr.ap-south-1.amazonaws.com/devopsexam:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_APP
              value: "app.py"
            - name: FLASK_ENV
              value: "production"
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "rootpass"
            - name: MYSQL_DATABASE
              value: "devops_exam"
          volumeMounts:
            - name: flask-volume
              mountPath: /app
            - name: frontend-volume
              mountPath: /app/templates
      volumes:
        - name: flask-volume
          hostPath:
            path: ./backend
        - name: frontend-volume
          hostPath:
            path: ./frontend
---
apiVersion: v1
kind: Service
metadata:
  name: flask
  namespace: devops-exam
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: flask
