# service.yml (updated)
apiVersion: v1
kind: Service
metadata:
  name: devopsexamapp-service
  namespace: webapps
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
spec:
  type: LoadBalancer
  selector:
    app: devopsexamapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000  # Matches Flask port

  
